# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "ZigStar CC2538 FW Flasher"
version: "1.1.0"
slug: "zigstar-cc2538-flasher"
description: "Flash Z-Stack 3.x.0 coordinator firmware to ZigStar CC2538 based coordinators over the network using cc2538-bsl"
url: "https://github.com/bytelink-ai/zigstar/tree/main/zigstar-cc2538-flasher"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  device_ip: "192.168.1.100"
  device_port: "23"
  firmware_file: ""
  firmware_url: "https://github.com/Koenkk/Z-Stack-firmware/raw/Z-Stack_3.x.0_router_20250403/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20250321.zip"
  firmware_zip_inner: "CC2652RB_coordinator_20250321.hex.bin" # preselected Z-Stack 3.x.0 coordinator firmware
  baud_rate: "115200"
  prepare_device: true
  wait_time: 30
  erase_flash: true
  verify_flash: true
schema:
  device_ip: "str"
  device_port: "str"
  firmware_file: "str?"
  firmware_url: "str"
  firmware_zip_inner: "str"
  baud_rate: "str"
  prepare_device: "bool"
  wait_time: "int(10,120)"
  erase_flash: "bool"
  verify_flash: "bool"
image: "ghcr.io/bytelink-ai/{arch}-addon-zigstar-cc2538-flasher"
